[tool.poetry]
name = "flask-app"
description = ""
authors = ["Ran Schreiber <ransch7@gmail.com>"]
version = "0.1.0"
packages = [{include = "flask_app"}]

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
flask = "~3"
flask-cors = "~4"
psycopg = {extras = ["binary", "pool"], version = "~3"}
pyparsing = "~3"
waitress = "~3"
pandas = "~2"
oracle-mistakes = {path = "../impl/dist/oracle_mistakes-0.1.0.tar.gz"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
